using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

// General Information about an assembly is controlled through the following 
// set of attributes. Change these attribute values to modify the information
// associated with an assembly.
[assembly: AssemblyTitle("Carbonium")]
[assembly: AssemblyDescription("")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("Carbonium")]
[assembly: AssemblyProduct("Carbonium")]
[assembly: AssemblyCopyright("Copyright © Carbonium")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]

// Setting ComVisible to false makes the types in this assembly not visible 
// to COM components.  If you need to access a type in this assembly from 
// COM, set the ComVisible attribute to true on that type.
[assembly: ComVisible(false)]

// The following GUID is for the ID of the typelib if this project is exposed to COM
[assembly: Guid("e05b6047-0a14-41a6-b178-4bb397e05d85")]

// This is automatically generated by SetBuildVersion.csproj. 
// To set a new version:
// 1. Specify new version in build\package.json.
// 2. cd build
// 3. gulp assembly-info
// Use only major or minor version. Build and revision are set during builds.
[assembly: AssemblyVersion("2.0.0.0")]